authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .views import account_activation_sent
from authentication import views as core
from authentication.forms import SetPasswordForm

app_name = 'authentication'

urlpatterns = [

    url(r'^login/$', core.LoginView.as_view(), name='login'),
    url(r'^signup/$', core.RegisterView.as_view(), name='signup'),
    url(r'^logout/$', core.LogoutView.as_view(), name='logout'),

    url(r'^password_reset/$',
        auth_views.password_reset,
        {
            'template_name': 'authentication/registration/password_reset_form.html',
            'from_email':'no-reply@mail.quizer.com',
            'email_template_name':'authentication/registration/password_reset_email.html',
            'post_reset_redirect':'authentication:password_reset_done',
        },
        name='password_reset'
        ),
    url(r'^password_reset/done/$',
        auth_views.password_reset_done,
        {'template_name': 'authentication/registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core.activate, name='activate'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {
            'post_reset_redirect':'authentication:password_reset_complete',
            'template_name': 'authentication/registration/password_reset_confirm.html',
            'set_password_form': SetPasswordForm

        },
        name='password_reset_confirm'
        ),
    url(r'^reset/done/$',
        auth_views.password_reset_complete,
        {
            'template_name': 'authentication/registration/password_reset_complete.html'
        },
        name='password_reset_complete'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),

]

core/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student$', views.students, name='students'),
    url(r'^student/add$', views.create_student, name='student_add'),


    url(r'^teacher$', views.teachers, name='teacher'),
    url(r'^teacher/(?P<pk>\d+)/resend_email$', views.invite_teacher, name='teacher_invite'),
    url(r'^teacher/add$', views.create_teacher, name='teacher_add'),
    url(r'^teacher/add_success$', views.create_teacher_success, name='teacher_add_success'),

]

quizer/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('question/', include("formly.urls")),

    path('', include('authentication.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
]

# serve static and media files in development, add debug toolbar urls
if settings.DEBUG:
    urlpatterns = urlpatterns \
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # django debug toolbar
    import debug_toolbar
    urlpatterns = [
                      path(r'__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth import get_user_model

from django.utils.translation import gettext, gettext_lazy as _


class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'first_name', 'last_name', 'password1', 'password2',)

    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification. (also For No Spelling Mistakes)"),
    )

    first_name = forms.CharField(required=False)

    # def _post_clean(self):
    #     super()._post_clean()
    #     # Validate the email hasn't been used by an account yet
    #     #  after self.instance is updated with form data
    #     # by super().
    #     email = self.cleaned_data.get("email")
    #     if Email.objects.filter().exists():
    #         self.add_error('email', error)


class SignInForm(AuthenticationForm):
    username = UsernameField(
        max_length=254,
        label='Username or Email'  # the form is extended to edit this label
    )


class StudentSignInForm(AuthenticationForm):
    username = forms.ChoiceField(
            choices=[(x,'Student #{}'.format(x)) for x in range(1,51)],
        label='Registration Number'
    )

    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.HiddenInput,
        initial='student'
    )



from django.template import loader
from django.conf import settings

from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMultiAlternatives
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from authentication.models import User


class AdminRegisterUserForm(forms.Form):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()

    def save(self):
        email = self.cleaned_data.get('email')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        # access_level = self.cleaned_data.get('access_level')

        account = User.objects.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=User.objects.make_random_password(),
            # email_verified=True,
            is_active=False,
            is_staff=True,

        )

        self.invite(account)

        return account

    def invite(self, account):
        account.is_active = True
        account.save()

        use_https = False
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        context = {
            'email': account.email,
            'domain': settings.HOST + (':{}'.format(settings.PORT)) if settings.PORT else '',
            'site_name': 'site_name',
            'uid': urlsafe_base64_encode(force_bytes(account.pk)).decode(),
            'user': account,
            'token': default_token_generator.make_token(account),
            'protocol': 'https' if use_https else 'http',
        }

        self.send_mail(
            'authentication/registration/account_activation_subject.txt',
            'authentication/registration/password_reset_email.html',
            context,
            'no-reply@accounts.quizer.com',
            account.email,
            None,
        )


class StudentRegistrationForm(forms.Form):
    registration_number = forms.CharField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    def save(self):
        email = self.cleaned_data.get('registration_number')
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        # access_level = self.cleaned_data.get('access_level')

        account = User.objects.create_user(
            username=email,
            first_name=first_name,
            last_name=last_name,
            password=User.objects.make_random_password(),
            is_active=True,

        )

        return account


from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)


class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        self.user.is_active = True
        if commit:
            self.user.save()
        return self.user

authentication/views.py
import logging

from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.contrib.auth import login
from authentication.forms import SignInForm,StudentSignInForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
from django.utils.http import is_safe_url
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect, ensure_csrf_cookie
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView

from .forms import SignUpForm
from django.contrib.auth import get_user_model
from authentication.models import Email
from django.conf import settings

Account = get_user_model()

# Create your views here.
log = logging.getLogger(__name__)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        primary_email = Email.objects.get(email=user.email)
        primary_email.is_verified = True
        primary_email.save()

        login(request, user, backend='authentication.backends.username_or_email.UsernameEmailBackend')
        return redirect(settings.INDEX_URL)
    else:
        return render(request, 'authentication/account_activation_invalid.html')


def account_activation_sent(request):
    return render(request, 'authentication/account_activation_sent.html')


class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    template_name = 'authentication/login.html'
    # template_name = 'partials/dash_menu.html'
    # template_name = 'web/dash_test.html'
    success_url = '/'
    form_class = SignInForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(ensure_csrf_cookie)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        # request.session.set_test_cookie()
        # log.info("Test Cookie Set")
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['student_sign_in_form'] = StudentSignInForm()

        return context

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        # if self.request.session.test_cookie_worked():
        #    log.info('test cookie worked')
        #    self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class RegisterView(FormView):
    """
    Provides the ability to register user with a username and password
    """
    template_name = 'authentication/register.html'
    success_url = '/account_activation_sent/'
    form_class = SignUpForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password', 'password2'))
    @method_decorator(csrf_protect)
    @method_decorator(ensure_csrf_cookie)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        # request.session.set_test_cookie()
        # log.info("Test Cookie Set")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        user.is_staff = True
        user.is_active = False
        user.save()

        if not user.is_superuser:
            pass

        # auth_login(self.request, user)

        return super(RegisterView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    template_name = 'core/logout.html'
    url = '/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

authentication/templates/authentication/account_activation_email.html
{% autoescape off %}
Hi {{ user.get_full_name }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}
{% endautoescape %}

authentication/templates/authentication/account_activation_invalid.html
<p>The confirmation link was invalid, possibly because it has already been used.</p>

authentication/templates/authentication/account_activation_sent.html
{% extends 'authentication/layout.html' %}

{% block content %}

    <div class="card" >
  <div class="card-body">
    <h5 class="card-title">Registration</h5>
    <h6 class="card-subtitle mb-2 text-muted">Registration Request Successful</h6>
    <p class="card-text">
    An activation link will be sent to your email address after admin approves  registration. <br>
                    You confirm your email address to complete registration.
    </p>
  </div>
</div>

{% endblock %}

authentication/templates/authentication/layout.html
{% extends 'application.html' %}
{% block app %}
    <div class="container">
        <div class="spacer" style="margin-top: 10px"></div>
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

authentication/templates/authentication/login.html
{% extends 'authentication/layout.html' %}
{% load web_filters %}
{% load static %}
{% block content %}

        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Staff Login</h5>

                        <form class="form-type-material col-md-12" method="post">
                            {% csrf_token %}

                            {% if form.errors %}
                                <p>{{ form.errors }}</p>
                            {% endif %}

                            {% for field in form %}
                                <div>
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <p style="color: red">Error {{ error }}</p>
                                        {% endfor %}
                                    {% endif %}
                                    <div class="form-group">
                                        {{ field.label_tag }}
                                        {{ field|addclass:'form-control' }}
                                        <span class="helptext">{{ field.help_text }}</span>
                                    </div>
                                </div>
                            {% endfor %}

                            <div class="form-group">
                                <input class="btn btn-primary form-control" type="submit" value="Login">
                            </div>

                        </form>

                    <div style="margin-top: 10px">

                                <a class="btn btn-primary"
                                   href="{% url 'authentication:password_reset' %}">Reset Password</a>
                                <a class="btn btn-primary"
                                   href="{% url 'authentication:signup' %}">Teacher Register</a>

                    </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Student Login</h5>

                    {% with student_sign_in_form as form %}

                         <form class="form-type-material col-md-12" method="post">
                            {% csrf_token %}

                            {% if form.errors %}
                                <p>{{ form.errors }}</p>
                            {% endif %}

                            {% for field in form %}
                                <div>
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <p style="color: red">Error {{ error }}</p>
                                        {% endfor %}
                                    {% endif %}
                                    <div class="form-group">
                                        {% if field.name == 'password' %}
                                            {% else %}
                                            {{ field.label_tag }}
                                        {% endif %}
                                        {{ field|addclass:'form-control' }}
                                        <span class="helptext">{{ field.help_text }}</span>
                                    </div>
                                </div>

                            {% endfor %}

                            <div class="form-group">
                                <input class="btn btn-primary form-control" type="submit" value="Login">
                            </div>

                        </form>


                    {% endwith %}


                    </div>
                </div>
            </div>
        </div>



{% endblock %}

authentication/templates/authentication/register.html
{% extends 'authentication/layout.html' %}
{% load web_filters %}

{% block content %}

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Register</h5>
            <h6 class="card-subtitle mb-2 text-muted">Teacher Registration</h6>
            <form id="register-form" action="/signup/" method="post"
                  role="form" style="display: block;">
                {% csrf_token %}

                {% for field in form %}
                    <div>
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p style="color: red">Error {{ error }}</p>
                            {% endfor %}
                        {% endif %}
                        <div class="form-group">
                            {#                                                {{ field.label_tag }}#}
                            <label for="{{ field.id_for_label }}"
                                   {% if field.field.required %}required{% endif %}>{{ field.label }}</label>
                            {{ field|addclass:'form-control' }}

                            <small>{{ field.help_text|safe }}</small>
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">

                    <input type="submit"
                           name="register-submit"

                           class="form-control btn btn-primary"
                           value="Register">

                </div>

            </form>
            You had an account?
            <a href="{% url 'authentication:login' %}" class="card-link">Login</a>
        </div>
    </div>

{% endblock %}