core/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student$', views.students, name='students'),
    url(r'^student/add$', views.create_student, name='student_add'),


    url(r'^teacher$', views.teachers, name='teacher'),
    url(r'^teacher/(?P<pk>\d+)/resend_email$', views.invite_teacher, name='teacher_invite'),
    url(r'^teacher/add$', views.create_teacher, name='teacher_add'),
    url(r'^teacher/add_success$', views.create_teacher_success, name='teacher_add_success'),

]

formly/urls.py
from django.conf.urls import url, include

from formly.views import design
from formly.views import results
from formly.views import run
from formly.views import views

app_name = 'formly'

urlpatterns = [

    url(r"^$", views.index, name="surveys"),
    # url(r"^archives/", views.archive, name="archives"),

    url(r'sets/',include(
        ([
             url(r'^(?P<set_pk>\d+)/', include([
                 url(r'^run/', include([
                     url(r'^$', run.run_survey),
                     url(r'^(?P<page_pk>\d+)/$', run.run_survey)
                 ]))
             ])),
         ],'sets')
    )),

    url(r"^surveys/", include((
        [
            # url(r"^$", design.survey_list, name="list"),
           url(r"^(?P<pk>\d+)/", include(([
               url(r'^results/', include([
                   url(r'^$', results.results),
                   url(r'^drafts$', results.results_draft),
               ])),
               url(r'^$', design.survey_daycares, name="detail"),
                url(r'^start$', views.survey_start),

              url(r'^results/', include([
                  url(r'^$', results.results),
                  url(r'^(?P<result_pk>\d+)/', include([
                      #url(r'^$', results.result),
                      url(r'^$', results.result_detail),
                      url(r'^(?P<result_page_pk>\d+)/$', results.result_detail),
                      #url(r"^details/(?P<result_page_pk>\d+)$", results.result_detail),
                      url(r'^run/', include([
                          url(r'^$', run.run_survey),
                          url(r'^(?P<page_pk>\d+)/$', run.run_survey)
                      ]))
                  ])),
              ])),
           ],app_name), namespace='survey'), ),
       ], app_name), namespace="surveys")),
    url(r"^design/$", design.survey_list, name="formly_dt_survey_list"),
    url(r"^design/surveys/(?P<pk>\d+)/$", design.survey_detail, name="formly_dt_survey_detail"),
    url(r"^design/surveys/create/$", design.survey_create, name="formly_dt_survey_create"),
    url(r"^design/surveys/(?P<pk>\d+)/change-name/$", design.survey_change_name, name="formly_dt_survey_change_name"),
    url(r"^design/surveys/(?P<pk>\d+)/duplicate/$", design.survey_duplicate, name="formly_dt_survey_duplicate"),
    url(r"^design/surveys/(?P<pk>\d+)/publish/$", design.survey_publish, name="formly_dt_survey_publish"),
    url(r"^design/surveys/(?P<pk>\d+)/pages/create/$", design.page_create, name="formly_dt_page_create"),
    url(r"^design/surveys/(?P<pk>\d+)/pages/edit/$", design.pages_edit, name="formly_dt_page_name_edit"),

    url(r"^design/pages/(?P<pk>\d+)/$", design.page_detail, name="formly_dt_page_detail"),
    url(r"^design/pages/(?P<pk>\d+)/fields/create/$", design.fields_create, name="formly_dt_field_create"),
    url(r"^design/pages/(?P<pk>\d+)/update/$", design.page_update, name="formly_dt_page_update"),

    url(r"^design/fields/(?P<pk>\d+)/update/$", design.field_update, name="formly_dt_field_update"),
    url(r"^design/fields/(?P<pk>\d+)/choices/add/$", design.field_add_choice, name="formly_dt_field_add_choice"),
    url(r"^design/fields/(?P<pk>\d+)/move-up/$", design.field_move_up, name="formly_dt_field_move_up"),
    url(r"^design/fields/(?P<pk>\d+)/move-down/$", design.field_move_down, name="formly_dt_field_move_down"),
    url(r"^design/choices/(?P<pk>\d+)/update/$", design.choice_update, name="formly_dt_choice_update"),
    url(r"^design/fields/(?P<pk>\d+)/delete/$", design.FieldDeleteView.as_view(), name="formly_dt_field_delete"),
    url(r"^design/choices/(?P<pk>\d+)/delete/$", design.ChoiceDeleteView.as_view(), name="formly_dt_choice_delete"),
    url(r"^design/pages/(?P<pk>\d+)/delete/$", design.PageDeleteView.as_view(), name="formly_dt_page_delete"),
    url(r"^design/surveys/(?P<pk>\d+)/delete/$", design.SurveyDeleteView.as_view(), name="formly_dt_survey_delete"),

    url(r"^ajax/design/choices/(?P<pk>\d+)/delete/$", design.choice_delete, name="formly_dt_ajax_choice_delete"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/likert-scales/(?P<scale_pk>\d+)/set/$", design.likert_scale_set,
        name="formly_dt_ajax_likert_scale_set"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/likert-scales/create/$", design.likert_scale_create,
        name="formly_dt_ajax_likert_scale_create"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/rating-scales/(?P<scale_pk>\d+)/set/$", design.rating_scale_set,
        name="formly_dt_ajax_rating_scale_set"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/rating-scales/create/$", design.rating_scale_create,
        name="formly_dt_ajax_rating_scale_create"),

    # url(r"^run/survey/(?P<daycare_pk>\d+)/(?P<survey_pk>\d+)/(?P<page_pk>\d+)/$", run.take_survey, name="formly_rt_take_survey"),
    # url(r"^run/survey/(?P<daycare_pk>\d+)/(?P<survey_pk>\d+)/$", run.take_survey, name="formly_rt_take_survey"),

    #
    url(r"^run/ajax/choice-question/(?P<pk>\d+)/$", run.choice_question, name="formly_rt_choice_question"),

    url(r"^results/survey/(?P<pk>\d+)/$", results.survey_results, name="formly_survey_results"),
    url(r"^results/(?P<pk>\d+)/$", results.results, name="survey_results"),

    url(r"^results/(?P<pk>\d+)/(?P<result_pk>\d+)/$", results.result, name="survey_results"),
    url(r"^results/(?P<pk>\d+)/(?P<result_pk>\d+)/details/(?P<result_page_pk>\d+)$", results.result_detail)
]

quizer/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('question/', include("formly.urls")),

    path('', include('authentication.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
]

# serve static and media files in development, add debug toolbar urls
if settings.DEBUG:
    urlpatterns = urlpatterns \
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # django debug toolbar
    import debug_toolbar
    urlpatterns = [
                      path(r'__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from authentication.models import User

# Create your views here.


def index(request):
    context = {}

    teachers = User.objects.filter(is_staff=True)
    students = User.objects.filter(is_staff=False,is_superuser=False)
    # teachers = User.objects.filter(is_staff=True)
    from formly.models import Survey
    questions = Survey.objects.all()

    context['teachers'] = teachers
    context['students'] = students
    context['questions'] = questions
    return render(request, 'core/dashboard.html',context)


def teachers(request):
    context = {}

    teacher_list = User.objects.filter(is_staff=True).order_by('-id')
    context['teachers'] = teacher_list

    return render(request, 'core/teachers.html',context)


def students(request):
    context = {}

    student_list = User.objects.filter(is_staff=False)
    context['students'] = student_list

    return render(request, 'core/students.html',context)


from authentication.forms import AdminRegisterUserForm


def create_teacher(request):
    context = {}

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        account_form = AdminRegisterUserForm(request.POST, request.FILES)
        account_form.access_level = User.TEACHER
        if account_form.is_valid():
            account = account_form.save()

            return HttpResponseRedirect('/teacher/add_success')

        else:
            print(request.POST)
            print(account_form.errors)
            # context['form'] = form

    # If this is a GET (or any other method) create the default form.
    else:
        account_form = AdminRegisterUserForm()
        context['form'] = account_form

    return render(request, 'core/teacher_create.html',context)


def invite_teacher(request,pk):
    teacher = User.objects.get(pk=pk)
    context = {}

    account_form = AdminRegisterUserForm()

    account_form.invite(teacher)

    return render(request, 'core/teacher_invite_success.html',context)


from authentication.forms import StudentRegistrationForm


def create_student(request):
    context = {}

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        form = StudentRegistrationForm(request.POST, request.FILES)
        form.access_level = User.STUDENT

        if form.is_valid():
            student = form.save()

            return HttpResponseRedirect('/student')

        else:
            print(request.POST)
            print(form.errors)
            # context['form'] = form

    # If this is a GET (or any other method) create the default form.
    else:
        form = StudentRegistrationForm()
        context['form'] = form

    return render(request, 'core/student_create.html',context)

def create_teacher_success(request):
    return render(request,'core/user_create_success.html')

core/templates/application.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#ff6600">
    <link rel="shortcut icon" href="favicon.ico">

    <title>Quizer</title>

    {#    <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,500,100,700%7Dosis:400,500" rel="stylesheet">#}
    {#    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">#}
    {#    <!-- Google Fonts-->#}

    {% load staticfiles %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <style>
        body {
          background: #ebfbfa;
          font: 300 16px/22px "Lato", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
    </style>

</head>

<body>

{% block app %}{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>


</body>
</html>

core/templates/layout.html
{% extends 'application.html' %}

{% load active_link_tags %}


{% block app %}
    <div class="container">
        <!-- Navigation -->
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark"
             style="background-color: #36d4ce;border-bottom-left-radius: .25rem;border-bottom-right-radius: .25rem">
            <a class="navbar-brand" href="/">Quizer</a>
            {#        <a class="navbar-brand" href="/">#}
            {#            <img src="{% static 'logo.png' %}" width="30" height="30" alt="">#}
            {#        </a>#}

            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav mr-auto">

                    {% if request.user.is_superuser %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'core:teacher' %}">
                                Teachers <span class="sr-only">(current)</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:students' %}">Students</a>
                        </li>

                    {% elif request.user.is_staff %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:students' %}">Students</a>
                        </li>

                    {% endif %}



                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'formly:surveys' %}">Questions</a>
                    </li>


                </div>
                {% block nav_form %}
                    <form class="form-inline col-md-5">
                        <input class="form-control col-md-12" type="search" placeholder="Search">
                    </form>
                {% endblock nav_form %}
                <ul class="navbar-nav">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                           href="#!"
                           id="navbarDropdownMenuLink"
                           data-toggle="dropdown"
                           aria-haspopup="true"
                           aria-expanded="false">
                            {% if request.user.is_authenticated %}
                                {{ request.user }}
                            {% else %}
                                Hi!
                            {% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right"
                             aria-labelledby="navbarDropdownMenuLink">
                            {% if request.user.is_authenticated %}

                                <a class="dropdown-item" href="/logout/">Logout</a>
                                {% if request.user.is_superuser %}
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" target="_blank" href="/admin/">Admin</a>
                                {% endif %}
                            {% else %}

                                <a class="dropdown-item" href="/login/">Login</a>
                                <a class="dropdown-item" href="/signup/">Register</a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="spacer" style="margin-top: 10px"></div>
        {% block content %}
        {% endblock %}
    </div>

{% endblock %}