core/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student$', views.students, name='students'),
    url(r'^student/add$', views.create_student, name='student_add'),


    url(r'^teacher$', views.teachers, name='teacher'),
    url(r'^teacher/(?P<pk>\d+)/resend_email$', views.invite_teacher, name='teacher_invite'),
    url(r'^teacher/add$', views.create_teacher, name='teacher_add'),
    url(r'^teacher/add_success$', views.create_teacher_success, name='teacher_add_success'),

]

formly/urls.py
from django.conf.urls import url, include

from formly.views import design
from formly.views import results
from formly.views import run
from formly.views import views

app_name = 'formly'

urlpatterns = [

    url(r"^$", views.index, name="surveys"),
    # url(r"^archives/", views.archive, name="archives"),

    url(r'sets/',include(
        ([
             url(r'^(?P<set_pk>\d+)/', include([
                 url(r'^run/', include([
                     url(r'^$', run.run_survey),
                     url(r'^(?P<page_pk>\d+)/$', run.run_survey)
                 ]))
             ])),
         ],'sets')
    )),

    url(r"^surveys/", include((
        [
            # url(r"^$", design.survey_list, name="list"),
           url(r"^(?P<pk>\d+)/", include(([
               url(r'^results/', include([
                   url(r'^$', results.results),
                   url(r'^drafts$', results.results_draft),
               ])),
               url(r'^$', design.survey_daycares, name="detail"),
                url(r'^start$', views.survey_start),

              url(r'^results/', include([
                  url(r'^$', results.results),
                  url(r'^(?P<result_pk>\d+)/', include([
                      #url(r'^$', results.result),
                      url(r'^$', results.result_detail),
                      url(r'^(?P<result_page_pk>\d+)/$', results.result_detail),
                      #url(r"^details/(?P<result_page_pk>\d+)$", results.result_detail),
                      url(r'^run/', include([
                          url(r'^$', run.run_survey),
                          url(r'^(?P<page_pk>\d+)/$', run.run_survey)
                      ]))
                  ])),
              ])),
           ],app_name), namespace='survey'), ),
       ], app_name), namespace="surveys")),
    url(r"^design/$", design.survey_list, name="formly_dt_survey_list"),
    url(r"^design/surveys/(?P<pk>\d+)/$", design.survey_detail, name="formly_dt_survey_detail"),
    url(r"^design/surveys/create/$", design.survey_create, name="formly_dt_survey_create"),
    url(r"^design/surveys/(?P<pk>\d+)/change-name/$", design.survey_change_name, name="formly_dt_survey_change_name"),
    url(r"^design/surveys/(?P<pk>\d+)/duplicate/$", design.survey_duplicate, name="formly_dt_survey_duplicate"),
    url(r"^design/surveys/(?P<pk>\d+)/publish/$", design.survey_publish, name="formly_dt_survey_publish"),
    url(r"^design/surveys/(?P<pk>\d+)/pages/create/$", design.page_create, name="formly_dt_page_create"),
    url(r"^design/surveys/(?P<pk>\d+)/pages/edit/$", design.pages_edit, name="formly_dt_page_name_edit"),

    url(r"^design/pages/(?P<pk>\d+)/$", design.page_detail, name="formly_dt_page_detail"),
    url(r"^design/pages/(?P<pk>\d+)/fields/create/$", design.fields_create, name="formly_dt_field_create"),
    url(r"^design/pages/(?P<pk>\d+)/update/$", design.page_update, name="formly_dt_page_update"),

    url(r"^design/fields/(?P<pk>\d+)/update/$", design.field_update, name="formly_dt_field_update"),
    url(r"^design/fields/(?P<pk>\d+)/choices/add/$", design.field_add_choice, name="formly_dt_field_add_choice"),
    url(r"^design/fields/(?P<pk>\d+)/move-up/$", design.field_move_up, name="formly_dt_field_move_up"),
    url(r"^design/fields/(?P<pk>\d+)/move-down/$", design.field_move_down, name="formly_dt_field_move_down"),
    url(r"^design/choices/(?P<pk>\d+)/update/$", design.choice_update, name="formly_dt_choice_update"),
    url(r"^design/fields/(?P<pk>\d+)/delete/$", design.FieldDeleteView.as_view(), name="formly_dt_field_delete"),
    url(r"^design/choices/(?P<pk>\d+)/delete/$", design.ChoiceDeleteView.as_view(), name="formly_dt_choice_delete"),
    url(r"^design/pages/(?P<pk>\d+)/delete/$", design.PageDeleteView.as_view(), name="formly_dt_page_delete"),
    url(r"^design/surveys/(?P<pk>\d+)/delete/$", design.SurveyDeleteView.as_view(), name="formly_dt_survey_delete"),

    url(r"^ajax/design/choices/(?P<pk>\d+)/delete/$", design.choice_delete, name="formly_dt_ajax_choice_delete"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/likert-scales/(?P<scale_pk>\d+)/set/$", design.likert_scale_set,
        name="formly_dt_ajax_likert_scale_set"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/likert-scales/create/$", design.likert_scale_create,
        name="formly_dt_ajax_likert_scale_create"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/rating-scales/(?P<scale_pk>\d+)/set/$", design.rating_scale_set,
        name="formly_dt_ajax_rating_scale_set"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/rating-scales/create/$", design.rating_scale_create,
        name="formly_dt_ajax_rating_scale_create"),

    # url(r"^run/survey/(?P<daycare_pk>\d+)/(?P<survey_pk>\d+)/(?P<page_pk>\d+)/$", run.take_survey, name="formly_rt_take_survey"),
    # url(r"^run/survey/(?P<daycare_pk>\d+)/(?P<survey_pk>\d+)/$", run.take_survey, name="formly_rt_take_survey"),

    #
    url(r"^run/ajax/choice-question/(?P<pk>\d+)/$", run.choice_question, name="formly_rt_choice_question"),

    url(r"^results/survey/(?P<pk>\d+)/$", results.survey_results, name="formly_survey_results"),
    url(r"^results/(?P<pk>\d+)/$", results.results, name="survey_results"),

    url(r"^results/(?P<pk>\d+)/(?P<result_pk>\d+)/$", results.result, name="survey_results"),
    url(r"^results/(?P<pk>\d+)/(?P<result_pk>\d+)/details/(?P<result_page_pk>\d+)$", results.result_detail)
]

quizer/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('question/', include("formly.urls")),

    path('', include('authentication.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
]

# serve static and media files in development, add debug toolbar urls
if settings.DEBUG:
    urlpatterns = urlpatterns \
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # django debug toolbar
    import debug_toolbar
    urlpatterns = [
                      path(r'__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

formly/models.py
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Max
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from .fields import LimitedMultipleChoiceField, MultipleTextField
from .forms.widgets import LikertSelect, MultiTextWidget, RatingSelect


@python_2_unicode_compatible
class OrdinalScale(models.Model):
    ORDINAL_KIND_LIKERT = "likert"
    ORDINAL_KIND_RATING = "rating"
    ORDINAL_KIND_CHOICES = [
        (ORDINAL_KIND_LIKERT, "Likert Scale"),
        (ORDINAL_KIND_RATING, "Rating Scale")
    ]

    name = models.CharField(max_length=100)
    kind = models.CharField(max_length=6, choices=ORDINAL_KIND_CHOICES)

    def __str__(self):
        return "{} [{}]".format(self.name, ", ".join([str(c) for c in self.choices.order_by("score")]))


@python_2_unicode_compatible
class OrdinalChoice(models.Model):
    scale = models.ForeignKey(OrdinalScale, related_name="choices",on_delete=models.CASCADE)
    label = models.CharField(max_length=100)
    score = models.IntegerField()

    def __str__(self):
        return "{} ({})".format(self.label, self.score)

    class Meta:
        unique_together = [("scale", "score"), ("scale", "label")]


@python_2_unicode_compatible
class Survey(models.Model):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="created_surveys",on_delete=models.CASCADE)

    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    published = models.DateTimeField(null=True, blank=True, default=timezone.now)

    def save(self, *args, **kwargs):
        if self.pk:
            self.updated = timezone.now()
        return super(Survey, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("formly:formly_dt_survey_detail", kwargs={"pk": self.pk})

    def duplicate(self):  # @@@ This could like use with some refactoring
        survey = Survey.objects.get(pk=self.pk)
        survey.pk = None
        survey.save()
        survey.pages.all().delete()

        pages = {}
        page_targets = []
        choice_targets = []

        for page in Survey.objects.get(pk=self.pk).pages.all():
            orig_page_target = page.target
            orig_page_pk = page.pk
            page.pk = None
            page.survey = survey
            page.target = None
            page.save()
            pages[orig_page_pk] = page
            if orig_page_target:
                page_targets.append({
                    "page": page,
                    "orig_target_pk": orig_page_target.pk
                })
            for field in Page.objects.get(pk=orig_page_pk).fields.all():
                orig_field_pk = field.pk
                field.pk = None
                field.survey = survey
                field.page = page
                field.save()
                for choice in Field.objects.get(pk=orig_field_pk).choices.all():
                    orig_target = choice.target
                    choice.pk = None
                    choice.field = field
                    choice.target = None
                    choice.save()
                    if orig_target:
                        choice_targets.append({
                            "choice": choice,
                            "orig_target_pk": orig_target.pk
                        })

        for page_target in page_targets:
            page = page_target["page"]
            page.target = pages[page_target["orig_target_pk"]]
            page.save()
        for choice_target in choice_targets:
            choice = choice_target["choice"]
            choice.target = pages[choice_target["orig_target_pk"]]
            choice.save()

        return survey

    @property
    def fields(self):
        for page in self.pages.all():
            for field in page.fields.all():
                yield field

    def publish(self):
        self.published = timezone.now()
        self.save()


@python_2_unicode_compatible
class Page(models.Model):
    survey = models.ForeignKey(Survey, related_name="pages",on_delete=models.CASCADE)
    page_num = models.PositiveIntegerField(null=True, blank=True)
    subtitle = models.CharField(max_length=255, blank=True)
    # Should be null when a FieldChoice on it's last field has a target.
    target = models.ForeignKey("self", null=True, blank=True,on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ("survey", "page_num")
        ]
        ordering = ["survey", "page_num"]

    def save(self, *args, **kwargs):
        if self.page_num is None:
            max_page = self.survey.pages.aggregate(Max("page_num"))
            self.page_num = (max_page.get("page_num__max") or 0) + 1
        return super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.label()

    def label(self):
        if self.subtitle:
            return self.subtitle
        else:
            return "Page %d" % self.page_num

    def get_absolute_url(self):
        return reverse("formly:formly_dt_page_detail", kwargs={"pk": self.pk})

    def move_up(self):
        try:
            other_field = self.survey.pages.order_by("-page_num").filter(
                page_num__lt=self.page_num
            )[0]
            existing = self.page_num
            other = other_field.page_num
            self.page_num = other
            other_field.page_num = existing
            other_field.save()
            self.save()
        except IndexError:
            return

    def move_down(self):
        try:
            other_field = self.page.fields.order_by("page_num").filter(
                page_num__gt=self.page_num
            )[0]
            existing = self.page_num
            other = other_field.page_num
            self.page_num = other
            other_field.page_num = existing
            other_field.save()
            self.save()
        except IndexError:
            return

    def fields_start_index(self):
        return Field.objects.filter(page__survey=self.survey, page__page_num__lt=self.page_num).count()

    def next_page(self, survey_result, user):
        target = self

        if self.completed(survey_result, user=user):
            try:
                target = self.survey.pages.get(
                    page_num=self.page_num + 1
                )
            except Page.DoesNotExist:
                target = None

            if self.target:
                target = self.target

            if target and target.completed(survey_result, user=user):
                target = target.next_page(survey_result, user=user)

        return target

    def completed(self, survey_result, user):
        return self.results.filter(result=survey_result, result__user=user).count() > 0

    def is_last_page(self):
        return self.next_page() is None


@python_2_unicode_compatible
class Field(models.Model):
    TEXT_FIELD = 0
    TEXT_AREA = 1
    RADIO_CHOICES = 2
    DATE_FIELD = 3
    SELECT_FIELD = 4
    CHECKBOX_FIELD = 5
    MEDIA_FIELD = 6
    BOOLEAN_FIELD = 7
    MULTIPLE_TEXT = 8
    LIKERT_FIELD = 9
    RATING_FIELD = 10

    FIELD_TYPE_CHOICES = [
        (TEXT_FIELD, "Free Response - One Line"),
        (TEXT_AREA, "Free Response - Box"),
        #(RADIO_CHOICES, "Multiple Choice - Pick One"),
        #(SELECT_FIELD, "Multiple Choice - Pick One (Dropdown)"),
        #(CHECKBOX_FIELD, "Multiple Choice - Can select multiple answers"),
        #(DATE_FIELD, "Date"),
        #(MEDIA_FIELD, "File Upload"),
        #(BOOLEAN_FIELD, "True/False"),
        #(MULTIPLE_TEXT, "Multiple Free Responses - Single Lines"),
        #(LIKERT_FIELD, "Likert Scale"),
        #(RATING_FIELD, "Rating Scale")
    ]

    survey = models.ForeignKey(Survey, related_name="fields",on_delete=models.CASCADE)  # Denorm
    page = models.ForeignKey(Page, null=True, blank=True, related_name="fields",on_delete=models.CASCADE)
    label = models.TextField()
    field_type = models.IntegerField(choices=FIELD_TYPE_CHOICES)
    scale = models.ForeignKey(OrdinalScale, default=None, null=True, blank=True, related_name="fields",on_delete=models.CASCADE)
    help_text = models.TextField(blank=True)
    ordinal = models.IntegerField()
    maximum_choices = models.IntegerField(null=True, blank=True)
    # Should this be moved to a separate Constraint model that can also
    # represent cross field constraints
    required = models.BooleanField(default=False)
    expected_answers = models.PositiveSmallIntegerField(default=1)

    # def clean(self):
    #     super(Field, self).clean()
    #     if self.page is None:
    #         if self.target_choices.count() == 0:
    #             raise ValidationError(
    #                 "A question not on a page must be a target of a choice from another question"
    #             )

    def save(self, *args, **kwargs):
        self.full_clean()
        if not self.pk and self.page is not None:
            self.ordinal = (self.page.fields.aggregate(
                Max("ordinal")
            )["ordinal__max"] or 0) + 1
        return super(Field, self).save(*args, **kwargs)

    def move_up(self):
        try:
            other_field = self.page.fields.order_by("-ordinal").filter(
                ordinal__lt=self.ordinal
            )[0]
            existing = self.ordinal
            other = other_field.ordinal
            self.ordinal = other
            other_field.ordinal = existing
            other_field.save()
            self.save()
        except IndexError:
            return

    def move_down(self):
        try:
            other_field = self.page.fields.order_by("ordinal").filter(

formly/forms/forms.py
from django import forms
from formly.models import SurveyResult


class SurveyResultForm(forms.ModelForm):

    # survey = forms.C(widget=forms.HiddenInput())
    # user = forms.ModelChoiceField(widget=forms.HiddenInput())
    # daycare = forms.ModelChoiceField(widget=forms.HiddenInput())
    # date_submitted = forms.DateField(widget=forms.HiddenInput())

    class Meta:
        model = SurveyResult
        exclude = ()

formly/templates/formly/design/_field_edit.html
{% load bootstrap %}

{% if field_form %}
    <p>{{ form.errors }}</p>

    <form action="{% url "formly:formly_dt_field_update" pk=selected_field.pk %}" method="post" class="well">

        {% csrf_token %}
        {{ field_form|bootstrap }}
        <div class="form-actions">
            <input type="hidden" name="action" value="field_update"/>
{#            <input type="hidden" name="action" value="field_update">#}
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-danger" href="{% url "formly:formly_dt_field_delete" pk=selected_field.pk %}">Delete</a>
        </div>
    </form>

    {% if selected_field.needs_choices %}
        <h3>Choices</h3>
        <form action="{% url "formly:formly_dt_field_add_choice" selected_field.pk %}" method="post" class="well">
            {% csrf_token %}
            {{ field_choice_form|bootstrap }}
            <button class="btn btn-default btn-block">Add Choice</button>
        </form>
        <hr />
        <div class="list-group">
            {% for choice in selected_field.choices.all %}
            <div class="list-group-item">
                <a class="btn btn-danger btn-xs pull-right ajax"
                   data-method="post"
                   data-replace-closest=".list-group-item"
                   href="{% url "formly:formly_dt_ajax_choice_delete" pk=choice.pk %}">
                    <i class="fa fa-fw fa-trash"></i>
                </a>
                {{ choice.label }}

            </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if selected_field.field_type == selected_field.LIKERT_FIELD %}
        <h3>Likert Scales</h3>
        <p class="lead">Select a Likert Scale</p>

        {% include "formly/design/_likert_scales.html" %}

        <h4>Add a new Likert scale</h4>
        {% include "formly/design/_likert_scale_form.html" %}

    {% endif %}

    {% if selected_field.field_type == selected_field.RATING_FIELD %}
        <h3>Rating Scales</h3>
        <p class="lead">Select a Rating Scale</p>

        {% include "formly/design/_rating_scales.html" %}

        <h4>Add a new Rating scale</h4>
        {% include "formly/design/_rating_scale_form.html" %}

    {% endif %}

{% endif %}

formly/templates/formly/design/_fields.html
{% if selected_page %}
    {#    <h2>Fields</h2>#}

    <div class="list-group">
        {% for field in fields %}
            <div data-ordinal="{{ field.ordinal }}" class="list-group-item"
                 {% if selected_field == field %}style="border-left: 5px solid #337ab7;"{% endif %}>
                <div>
                <span class="ordering btn-group pull-right">


{#                            <div class="form-actions">#}
{#            <input type="hidden" name="action" value="field_update"/>#}
{#            <input type="hidden" name="action" value="field_update">#}
{#            <button type="submit" class="btn btn-primary">Save</button>#}
{#            <a class="btn btn-danger" href="{% url "formly:formly_dt_field_delete" pk=field.pk %}">Delete</a>#}
{#        </div>#}
                    <a class="btn btn-xs btn-default ajax"
                       href="{% url "formly:formly_dt_field_move_up" pk=field.pk %}"
                       data-replace-inner=".fields"
                       data-method="post">
                       <i class="fa fa-fw fa-arrow-up"></i>
                    </a>
                    <a class="btn btn-xs btn-default ajax"
                       href="{% url "formly:formly_dt_field_move_down" pk=field.pk %}"
                       data-replace-inner=".fields"
                       data-method="post">
                       <i class="fa fa-fw fa-arrow-down"></i>
                    </a>
                </span>
                    <span>
                    <a href="{% url "formly:formly_dt_field_update" pk=field.pk %}">
                        {{ field.label }}
                    </a>
                </span>
                </div>

                <div>
                    {{ field.get_field_type_display }}
                </div>
                {% if field.choices.exists %}
                    <div>
                        {% for choice in field.choices.all %}
                            <span class="label label-default">{{ choice }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="text-muted">
                    <small>{{ field.help_text }}</small>
                </div>
            </div>

        {% empty %}

            <p>No Questions added on this page yet.</p>

        {% endfor %}
    </div>
    <hr/>
    <form action="{% url "formly:formly_dt_field_create" pk=selected_page.pk %}" method="post">
        {% csrf_token %}
        <button class="btn btn-mini btn-block btn-default"><i class="fa fa-fw fa-plus"></i> Add Question</button>
    </form>

{% endif %}

formly/templates/formly/design/_likert_scale.html
<div class="list-group-item">
    <a class="btn {% if scale == selected_field.scale %}btn-primary{% else %}btn-default{% endif %} btn-xs pull-right ajax" data-method="post" data-replace-closest=".likert-scales" href="{% url "formly_dt_ajax_likert_scale_set" selected_field.pk scale.pk %}">
        <i class="fa fa-fw fa-check"></i>
    </a>
    <div>
        <div>{{ scale.name }}</div>
        <small class="text-muted">
            {{ scale.choices.all|join:", " }}
        </small>
    </div>
</div>

formly/templates/formly/design/_likert_scale_form.html
{% load bootstrap %}
<form method="post" action="{% url "formly_dt_ajax_likert_scale_create" selected_field.pk %}" class="ajax likert-scale-form" data-replace=".likert-scale-form">
    {% csrf_token %}
    {{ likert_scale_form|bootstrap }}
    <button class="btn btn-sm btn-primary">Save</button>
</form>

formly/templates/formly/design/_likert_scales.html
<div class="list-group likert-scales">
    {% for scale in likert_scales %}
        {% include "formly/design/_likert_scale.html" %}
    {% endfor %}
</div>

formly/templates/formly/design/page_form.html
{% extends "formly/design/survey_edit_base.html" %}

{% load bootstrap %}

{% block body %}
    <header class="jumbotron subhead" id="overview">
      <h1>Modify Page</h1>
      <p class="lead">Edit the details for this page.</p>
    </header>

<form action="{% url "formly_dt_page_update" pk=page.pk %}" method="post" class="well">
    {% csrf_token %}
    <fieldset>
        {{ form|bootstrap }}
    </fieldset>
    <div class="form-actions">
        <input type="hidden" name="action" value="page_update" />
        <button type="submit" class="btn btn-primary">Save</button>
        <a class="btn" href="{{ page.survey.get_absolute_url }}">Cancel</a>
        <a class="btn btn-danger" href="{% url "formly:formly_dt_page_delete" pk=page.pk %}">Delete</a>
    </div>
</form>

<h3>Fields</h3>

<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>Label</th>
            <th>Type</th>
            <th>Help</th>
            <th>Required</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for field in page.fields.all %}
        <tr data-ordinal="{{ field.ordinal }}">
            <td class="ordering">
                <a class="btn btn-mini"
                   href="{% url "formly_dt_field_move_up" pk=field.pk %}">
                   Up
                </a>
                <a class="btn btn-mini"
                   href="{% url "formly_dt_field_move_down" pk=field.pk %}">
                   Down
                </a>
            </td>
            <td>
                <a href="{% url "formly_dt_field_update" pk=field.pk %}">
                    {{ field.label }}
                </a>
            </td>
            <td>
                {{ field.get_field_type_display }}
                {% if field.choices.exists %}
                    {% for choice in field.choices.all %}
                    <span class="label label-inverse">{{ choice }}</span>
                    {% endfor %}
                {% endif %}
            </td>
            <td>{{ field.help_text }}</td>
            <td>{{ field.required }}</td>
            <td>
                <a class="btn btn-danger btn-mini" href="{% url "formly:formly_dt_field_delete" pk=field.pk %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a class="btn btn-success btn-mini" data-toggle="modal" href="#new-field" ><i class="icon-plus icon-white"></i> Add Field</a>

<div class="modal hide" id="new-field">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Add Field</h3>
    </div>
    <form action="{% url "formly:formly_dt_page_update" pk=page.pk %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="action" value="field_add" />
        <div class="modal-body">
            {{ field_form|bootstrap }}
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="#" class="btn" data-dismiss="modal">Close</a>
        </div>
    </form>
</div>

{% endblock %}


{% block extra_body %}
    {{ block.super }}
    <script type="text/javascript">
    $(function() {
        $(".ordering a").click(function(evt) {
            evt.preventDefault()
            var $this = $(this)
            var $currentRow = $this.closest("tr")
            $.ajax({
                url: $this.attr("href"),
                type: "post",
                statusCode: {
                    200: function(data) {
                        window.location.href = data.location
                    }
                }
            });
        });
    });
    </script>
{% endblock %}

formly/templates/formly/design/survey_confirm_delete.html
{% extends "layout.html" %}

{% load bootstrap %}

{% block content %}
    <header class="jumbotron subhead" id="overview">
      <h1>Delete Question Set {{ survey }} </h1>
      <p class="lead">Please confirm the deletion of this Question Set.</p>
    </header>

    <form action="{% url "formly:formly_dt_survey_delete" pk=survey.pk %}" method="post">

        {% csrf_token %}
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <div class="form-actions">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn" href="{{ survey.get_absolute_url }}">Cancel</a>
        </div>
    </form>
{% endblock %}

formly/templates/formly/design/survey_list_detail.html
{% extends "layout.html" %}



{% block content %}

    <h4 class="">Question Set Edit</h4>

    {#    <a class="nav-link {% if active_tab == 'tab2' %} active{% endif %} " href="/surveys/{{ survey.pk }}/results/drafts">Drafts</a>#}



    <div class="card" style="">

        <div class="card-body">
            <h5 class="card-title">{{ survey }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ survey.creator }}</h6>

            <p class="card-text">{{ survey.created|date }}</p>


            <a href="{% url 'formly:formly_dt_survey_delete' pk=survey.pk %}" class="btn btn-danger">Delete</a>


        <a class="btn btn-danger" href="/question/design/surveys/{{ survey.pk }}/pages/edit/">Edit Pages</a>



        </div>
    </div>

    <div class="card" style="margin-top: 10px">

        <div class="card-body">
            <h5 class="card-title">Pages</h5>

            {% include "formly/design/_pages1.html" %}

            <form class="success text-center" style="margin-top: 10px;"
                  id="form-id"
                  action="{% url "formly:formly_dt_page_create" pk=survey.pk %}"
                  method="post">
                {% csrf_token %}

                <a class="btn btn-primary"
                   onclick="document.getElementById('form-id').submit();">Add New Page</a>

            </form>

{#          todo  <a href="/design/surveys/{{ selected_page.survey.pk }}/pages/edit/" class="btn btn-primary">Edit Pages</a>#}
        </div>
    </div>


{% endblock %}