core/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student$', views.students, name='students'),
    url(r'^student/add$', views.create_student, name='student_add'),


    url(r'^teacher$', views.teachers, name='teacher'),
    url(r'^teacher/(?P<pk>\d+)/resend_email$', views.invite_teacher, name='teacher_invite'),
    url(r'^teacher/add$', views.create_teacher, name='teacher_add'),
    url(r'^teacher/add_success$', views.create_teacher_success, name='teacher_add_success'),

]

formly/urls.py
from django.conf.urls import url, include

from formly.views import design
from formly.views import results
from formly.views import run
from formly.views import views

app_name = 'formly'

urlpatterns = [

    url(r"^$", views.index, name="surveys"),
    # url(r"^archives/", views.archive, name="archives"),

    url(r'sets/',include(
        ([
             url(r'^(?P<set_pk>\d+)/', include([
                 url(r'^run/', include([
                     url(r'^$', run.run_survey),
                     url(r'^(?P<page_pk>\d+)/$', run.run_survey)
                 ]))
             ])),
         ],'sets')
    )),

    url(r"^surveys/", include((
        [
            # url(r"^$", design.survey_list, name="list"),
           url(r"^(?P<pk>\d+)/", include(([
               url(r'^results/', include([
                   url(r'^$', results.results),
                   url(r'^drafts$', results.results_draft),
               ])),
               url(r'^$', design.survey_daycares, name="detail"),
                url(r'^start$', views.survey_start),

              url(r'^results/', include([
                  url(r'^$', results.results),
                  url(r'^(?P<result_pk>\d+)/', include([
                      #url(r'^$', results.result),
                      url(r'^$', results.result_detail),
                      url(r'^(?P<result_page_pk>\d+)/$', results.result_detail),
                      #url(r"^details/(?P<result_page_pk>\d+)$", results.result_detail),
                      url(r'^run/', include([
                          url(r'^$', run.run_survey),
                          url(r'^(?P<page_pk>\d+)/$', run.run_survey)
                      ]))
                  ])),
              ])),
           ],app_name), namespace='survey'), ),
       ], app_name), namespace="surveys")),
    url(r"^design/$", design.survey_list, name="formly_dt_survey_list"),
    url(r"^design/surveys/(?P<pk>\d+)/$", design.survey_detail, name="formly_dt_survey_detail"),
    url(r"^design/surveys/create/$", design.survey_create, name="formly_dt_survey_create"),
    url(r"^design/surveys/(?P<pk>\d+)/change-name/$", design.survey_change_name, name="formly_dt_survey_change_name"),
    url(r"^design/surveys/(?P<pk>\d+)/duplicate/$", design.survey_duplicate, name="formly_dt_survey_duplicate"),
    url(r"^design/surveys/(?P<pk>\d+)/publish/$", design.survey_publish, name="formly_dt_survey_publish"),
    url(r"^design/surveys/(?P<pk>\d+)/pages/create/$", design.page_create, name="formly_dt_page_create"),
    url(r"^design/surveys/(?P<pk>\d+)/pages/edit/$", design.pages_edit, name="formly_dt_page_name_edit"),

    url(r"^design/pages/(?P<pk>\d+)/$", design.page_detail, name="formly_dt_page_detail"),
    url(r"^design/pages/(?P<pk>\d+)/fields/create/$", design.fields_create, name="formly_dt_field_create"),
    url(r"^design/pages/(?P<pk>\d+)/update/$", design.page_update, name="formly_dt_page_update"),

    url(r"^design/fields/(?P<pk>\d+)/update/$", design.field_update, name="formly_dt_field_update"),
    url(r"^design/fields/(?P<pk>\d+)/choices/add/$", design.field_add_choice, name="formly_dt_field_add_choice"),
    url(r"^design/fields/(?P<pk>\d+)/move-up/$", design.field_move_up, name="formly_dt_field_move_up"),
    url(r"^design/fields/(?P<pk>\d+)/move-down/$", design.field_move_down, name="formly_dt_field_move_down"),
    url(r"^design/choices/(?P<pk>\d+)/update/$", design.choice_update, name="formly_dt_choice_update"),
    url(r"^design/fields/(?P<pk>\d+)/delete/$", design.FieldDeleteView.as_view(), name="formly_dt_field_delete"),
    url(r"^design/choices/(?P<pk>\d+)/delete/$", design.ChoiceDeleteView.as_view(), name="formly_dt_choice_delete"),
    url(r"^design/pages/(?P<pk>\d+)/delete/$", design.PageDeleteView.as_view(), name="formly_dt_page_delete"),
    url(r"^design/surveys/(?P<pk>\d+)/delete/$", design.SurveyDeleteView.as_view(), name="formly_dt_survey_delete"),

    url(r"^ajax/design/choices/(?P<pk>\d+)/delete/$", design.choice_delete, name="formly_dt_ajax_choice_delete"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/likert-scales/(?P<scale_pk>\d+)/set/$", design.likert_scale_set,
        name="formly_dt_ajax_likert_scale_set"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/likert-scales/create/$", design.likert_scale_create,
        name="formly_dt_ajax_likert_scale_create"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/rating-scales/(?P<scale_pk>\d+)/set/$", design.rating_scale_set,
        name="formly_dt_ajax_rating_scale_set"),
    url(r"^ajax/design/fields/(?P<field_pk>\d+)/rating-scales/create/$", design.rating_scale_create,
        name="formly_dt_ajax_rating_scale_create"),

    # url(r"^run/survey/(?P<daycare_pk>\d+)/(?P<survey_pk>\d+)/(?P<page_pk>\d+)/$", run.take_survey, name="formly_rt_take_survey"),
    # url(r"^run/survey/(?P<daycare_pk>\d+)/(?P<survey_pk>\d+)/$", run.take_survey, name="formly_rt_take_survey"),

    #
    url(r"^run/ajax/choice-question/(?P<pk>\d+)/$", run.choice_question, name="formly_rt_choice_question"),

    url(r"^results/survey/(?P<pk>\d+)/$", results.survey_results, name="formly_survey_results"),
    url(r"^results/(?P<pk>\d+)/$", results.results, name="survey_results"),

    url(r"^results/(?P<pk>\d+)/(?P<result_pk>\d+)/$", results.result, name="survey_results"),
    url(r"^results/(?P<pk>\d+)/(?P<result_pk>\d+)/details/(?P<result_page_pk>\d+)$", results.result_detail)
]

quizer/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('question/', include("formly.urls")),

    path('', include('authentication.urls')),
    path('', include('core.urls')),

    path('admin/', admin.site.urls),
]

# serve static and media files in development, add debug toolbar urls
if settings.DEBUG:
    urlpatterns = urlpatterns \
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # django debug toolbar
    import debug_toolbar
    urlpatterns = [
                      path(r'__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

formly/models.py
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Max
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from .fields import LimitedMultipleChoiceField, MultipleTextField
from .forms.widgets import LikertSelect, MultiTextWidget, RatingSelect


@python_2_unicode_compatible
class OrdinalScale(models.Model):
    ORDINAL_KIND_LIKERT = "likert"
    ORDINAL_KIND_RATING = "rating"
    ORDINAL_KIND_CHOICES = [
        (ORDINAL_KIND_LIKERT, "Likert Scale"),
        (ORDINAL_KIND_RATING, "Rating Scale")
    ]

    name = models.CharField(max_length=100)
    kind = models.CharField(max_length=6, choices=ORDINAL_KIND_CHOICES)

    def __str__(self):
        return "{} [{}]".format(self.name, ", ".join([str(c) for c in self.choices.order_by("score")]))


@python_2_unicode_compatible
class OrdinalChoice(models.Model):
    scale = models.ForeignKey(OrdinalScale, related_name="choices",on_delete=models.CASCADE)
    label = models.CharField(max_length=100)
    score = models.IntegerField()

    def __str__(self):
        return "{} ({})".format(self.label, self.score)

    class Meta:
        unique_together = [("scale", "score"), ("scale", "label")]


@python_2_unicode_compatible
class Survey(models.Model):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="created_surveys",on_delete=models.CASCADE)

    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    published = models.DateTimeField(null=True, blank=True, default=timezone.now)

    def save(self, *args, **kwargs):
        if self.pk:
            self.updated = timezone.now()
        return super(Survey, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("formly:formly_dt_survey_detail", kwargs={"pk": self.pk})

    def duplicate(self):  # @@@ This could like use with some refactoring
        survey = Survey.objects.get(pk=self.pk)
        survey.pk = None
        survey.save()
        survey.pages.all().delete()

        pages = {}
        page_targets = []
        choice_targets = []

        for page in Survey.objects.get(pk=self.pk).pages.all():
            orig_page_target = page.target
            orig_page_pk = page.pk
            page.pk = None
            page.survey = survey
            page.target = None
            page.save()
            pages[orig_page_pk] = page
            if orig_page_target:
                page_targets.append({
                    "page": page,
                    "orig_target_pk": orig_page_target.pk
                })
            for field in Page.objects.get(pk=orig_page_pk).fields.all():
                orig_field_pk = field.pk
                field.pk = None
                field.survey = survey
                field.page = page
                field.save()
                for choice in Field.objects.get(pk=orig_field_pk).choices.all():
                    orig_target = choice.target
                    choice.pk = None
                    choice.field = field
                    choice.target = None
                    choice.save()
                    if orig_target:
                        choice_targets.append({
                            "choice": choice,
                            "orig_target_pk": orig_target.pk
                        })

        for page_target in page_targets:
            page = page_target["page"]
            page.target = pages[page_target["orig_target_pk"]]
            page.save()
        for choice_target in choice_targets:
            choice = choice_target["choice"]
            choice.target = pages[choice_target["orig_target_pk"]]
            choice.save()

        return survey

    @property
    def fields(self):
        for page in self.pages.all():
            for field in page.fields.all():
                yield field

    def publish(self):
        self.published = timezone.now()
        self.save()


@python_2_unicode_compatible
class Page(models.Model):
    survey = models.ForeignKey(Survey, related_name="pages",on_delete=models.CASCADE)
    page_num = models.PositiveIntegerField(null=True, blank=True)
    subtitle = models.CharField(max_length=255, blank=True)
    # Should be null when a FieldChoice on it's last field has a target.
    target = models.ForeignKey("self", null=True, blank=True,on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ("survey", "page_num")
        ]
        ordering = ["survey", "page_num"]

    def save(self, *args, **kwargs):
        if self.page_num is None:
            max_page = self.survey.pages.aggregate(Max("page_num"))
            self.page_num = (max_page.get("page_num__max") or 0) + 1
        return super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.label()

    def label(self):
        if self.subtitle:
            return self.subtitle
        else:
            return "Page %d" % self.page_num

    def get_absolute_url(self):
        return reverse("formly:formly_dt_page_detail", kwargs={"pk": self.pk})

    def move_up(self):
        try:
            other_field = self.survey.pages.order_by("-page_num").filter(
                page_num__lt=self.page_num
            )[0]
            existing = self.page_num
            other = other_field.page_num
            self.page_num = other
            other_field.page_num = existing
            other_field.save()
            self.save()
        except IndexError:
            return

    def move_down(self):
        try:
            other_field = self.page.fields.order_by("page_num").filter(
                page_num__gt=self.page_num
            )[0]
            existing = self.page_num
            other = other_field.page_num
            self.page_num = other
            other_field.page_num = existing
            other_field.save()
            self.save()
        except IndexError:
            return

    def fields_start_index(self):
        return Field.objects.filter(page__survey=self.survey, page__page_num__lt=self.page_num).count()

    def next_page(self, survey_result, user):
        target = self

        if self.completed(survey_result, user=user):
            try:
                target = self.survey.pages.get(
                    page_num=self.page_num + 1
                )
            except Page.DoesNotExist:
                target = None

            if self.target:
                target = self.target

            if target and target.completed(survey_result, user=user):
                target = target.next_page(survey_result, user=user)

        return target

    def completed(self, survey_result, user):
        return self.results.filter(result=survey_result, result__user=user).count() > 0

    def is_last_page(self):
        return self.next_page() is None


@python_2_unicode_compatible
class Field(models.Model):
    TEXT_FIELD = 0
    TEXT_AREA = 1
    RADIO_CHOICES = 2
    DATE_FIELD = 3
    SELECT_FIELD = 4
    CHECKBOX_FIELD = 5
    MEDIA_FIELD = 6
    BOOLEAN_FIELD = 7
    MULTIPLE_TEXT = 8
    LIKERT_FIELD = 9
    RATING_FIELD = 10

    FIELD_TYPE_CHOICES = [
        (TEXT_FIELD, "Free Response - One Line"),
        (TEXT_AREA, "Free Response - Box"),
        #(RADIO_CHOICES, "Multiple Choice - Pick One"),
        #(SELECT_FIELD, "Multiple Choice - Pick One (Dropdown)"),
        #(CHECKBOX_FIELD, "Multiple Choice - Can select multiple answers"),
        #(DATE_FIELD, "Date"),
        #(MEDIA_FIELD, "File Upload"),
        #(BOOLEAN_FIELD, "True/False"),
        #(MULTIPLE_TEXT, "Multiple Free Responses - Single Lines"),
        #(LIKERT_FIELD, "Likert Scale"),
        #(RATING_FIELD, "Rating Scale")
    ]

    survey = models.ForeignKey(Survey, related_name="fields",on_delete=models.CASCADE)  # Denorm
    page = models.ForeignKey(Page, null=True, blank=True, related_name="fields",on_delete=models.CASCADE)
    label = models.TextField()
    field_type = models.IntegerField(choices=FIELD_TYPE_CHOICES)
    scale = models.ForeignKey(OrdinalScale, default=None, null=True, blank=True, related_name="fields",on_delete=models.CASCADE)
    help_text = models.TextField(blank=True)
    ordinal = models.IntegerField()
    maximum_choices = models.IntegerField(null=True, blank=True)
    # Should this be moved to a separate Constraint model that can also
    # represent cross field constraints
    required = models.BooleanField(default=False)
    expected_answers = models.PositiveSmallIntegerField(default=1)

    # def clean(self):
    #     super(Field, self).clean()
    #     if self.page is None:
    #         if self.target_choices.count() == 0:
    #             raise ValidationError(
    #                 "A question not on a page must be a target of a choice from another question"
    #             )

    def save(self, *args, **kwargs):
        self.full_clean()
        if not self.pk and self.page is not None:
            self.ordinal = (self.page.fields.aggregate(
                Max("ordinal")
            )["ordinal__max"] or 0) + 1
        return super(Field, self).save(*args, **kwargs)

    def move_up(self):
        try:
            other_field = self.page.fields.order_by("-ordinal").filter(
                ordinal__lt=self.ordinal
            )[0]
            existing = self.ordinal
            other = other_field.ordinal
            self.ordinal = other
            other_field.ordinal = existing
            other_field.save()
            self.save()
        except IndexError:
            return

    def move_down(self):
        try:
            other_field = self.page.fields.order_by("ordinal").filter(

formly/forms/forms.py
from django import forms
from formly.models import SurveyResult


class SurveyResultForm(forms.ModelForm):

    # survey = forms.C(widget=forms.HiddenInput())
    # user = forms.ModelChoiceField(widget=forms.HiddenInput())
    # daycare = forms.ModelChoiceField(widget=forms.HiddenInput())
    # date_submitted = forms.DateField(widget=forms.HiddenInput())

    class Meta:
        model = SurveyResult
        exclude = ()

formly/templates/portions/comment_form.html
<form action="{% url "formly:formly_survey_results" pk=survey.pk %}" class="row" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group col-md-12 col-xl-12">
        <label class="require" for="id_name">Name:</label>
        <div class="form-group">
           <textarea data-provide="summernote"
                     name="text" id="id_text" data-min-height="150" style="display: none;">
               Add Comment
           </textarea>
        </div>
    </div>
    <footer class="card-footer text-right">
       <button class="btn btn-bold btn-primary" type="submit">Submit</button>
    </footer>

</form>

formly/templates/portions/report_details.html
      <div class="main-content">
        <div class="container">


          <div class="card shadow-1">
            <header class="card-header bg-lightest">
              <div class="card-title flexbox">
                <img class="avatar" src="assets/img/avatar/2.jpg" alt="...">
                <div>
                  <h6 class="mb-0">Hossein Shams</h6>
                  <small>Today at 11:34 AM</small>
                </div>
              </div>
            </header>


            <div class="card-body">
              <p>Progressively administrate resource sucking methodologies and ethical action items. Globally monetize user-centric technology with low-risk high-yield action items. Collaboratively utilize cross-platform synergy whereas just in time.</p>
              <p>Monotonectally engage holistic benefits and pandemic solutions. Holisticly re-engineer multidisciplinary services and distributed solutions. Seamlessly simplify inexpensive relationships long-term high-impact methodologies. Conveniently innovate installed base. Proactively synergize holistic materials for standardized interfaces. Conveniently envisioneer strategic users whereas standards compliant e-business.</p>
              <hr>
              <h6 class="text-lighter text-uppercase mb-12">
                <i class="fa fa-paperclip mr-2"></i>
                <small>Attchments (3)</small>
              </h6>
              <div class="gap-items-2 gap-y" data-provide="photoswipe">
                <a class="d-inline-block" href="#"><img class="w-140px" src="assets/img/2.jpg" alt="..."></a>
                <a class="d-inline-block" href="#"><img class="w-140px" src="assets/img/3.jpg" alt="..."></a>
                <a class="d-inline-block" href="#"><img class="w-140px" src="assets/img/1.jpg" alt="..."></a>
              </div>

              <hr class="w-50px ml-0 mb-1">
              <p>Best regards,<br>Hossein Shams</p>
            </div>

          </div>




          <div class="card shadow-1">
            <header class="card-header bg-lightest">
              <div class="card-title flexbox">
                <img class="avatar" src="assets/img/avatar/1.jpg" alt="...">
                <div>
                  <h6 class="mb-0">Maryam Amiri <small class="sidetitle fs-11">Support Agent</small></h6>
                  <small>Today at 03:18 Pm</small>
                </div>
              </div>
            </header>


            <div class="card-body">
              <p>Credibly harness multidisciplinary ideas via alternative e-commerce. Intrinsicly transition interdependent best practices before resource sucking outsourcing. Dramatically deploy cross-platform growth strategies via 2.0 services. Competently incentivize customer directed infomediaries and leveraged markets. Synergistically syndicate goal-oriented innovation before magnetic mindshare. Interactively restore magnetic.</p>
            </div>

          </div>




          <div class="card shadow-1">
            <header class="card-header bg-lightest">
              <div class="card-title flexbox">
                <img class="avatar" src="assets/img/avatar/2.jpg" alt="...">
                <div>
                  <h6 class="mb-0">Hossein Shams</h6>
                  <small>Today at 06:38 PM</small>
                </div>
              </div>
            </header>

            <div class="card-body">
              <p>Thank you so much</p>
            </div>

          </div>


          <nav>
            <ul class="pagination justify-content-center">
              <li class="page-item disabled">
                <a class="page-link" href="#">
                  <span class="ti-arrow-left"></span>
                </a>
              </li>
              <li class="page-item active">
                <a class="page-link" href="#">1</a>
              </li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">4</a></li>
              <li class="page-item"><a class="page-link" href="#">5</a></li>
              <li class="page-item">
                <a class="page-link" href="#">
                  <span class="ti-arrow-right"></span>
                </a>
              </li>
            </ul>
          </nav>


          <br>
          <hr>

          <div class="row">
            <div class="col-md-12">
              <form class="card shadow-1" method="post" enctype="multipart/form-data">
                <h4 class="card-title"><strong>Reply</strong></h4>

                <div class="card-body">
                  <div class="form-group">
                    <label class="require">Content</label>
                    <textarea data-provide="summernote" data-toolbar="slim"></textarea>
                  </div>

                  <div class="form-group">
                    <label>Attachments</label>
                    <div class="input-group file-group">
                      <input type="text" class="form-control file-value" placeholder="Choose file..." readonly>
                      <input type="file" multiple>
                      <span class="input-group-btn">
                        <button class="btn btn-light file-browser" type="button"><i class="fa fa-upload"></i></button>
                      </span>
                    </div>
                  </div>
                </div>

                <footer class="card-footer text-right">
                  <button class="btn btn-bold btn-primary" type="submit">Submit</button>
                </footer>
              </form>
            </div>


{#            <div class="col-md-4">#}
{#              <div class="card">#}
{#                <h4 class="card-title"><strong>Close the topic</strong></h4>#}
{##}
{#                <div class="card-body">#}
{#                  <p>Does your problem fixed? So press the following button to mark the topic as resolved.</p>#}
{#                  <a class="btn btn-success btn-block" href="#">Close the topic</a>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
          </div>


        </div>
      </div>

formly/templates/portions/report_list.html
{load static}

      <div class="main-content">
        <div class="container">
          <div class="row gap-y gap-4">

            <div class="col-md-4 col-lg-3">
              <a class="btn btn-bold btn-block btn-primary" href="forum-single.html">Create a topic</a>
              <hr>
              <h5 class="mb-2">Filter by category</h5>
              <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                  <span class="badge badge-ring badge-danger"></span>
                  <a class="nav-link" href="#">General</a>
                </li>
                <li class="nav-item">
                  <span class="badge badge-ring badge-warning"></span>
                  <a class="nav-link" href="#">Bootstrap</a>
                </li>
                <li class="nav-item">
                  <span class="badge badge-ring badge-info"></span>
                  <a class="nav-link" href="#">Gruntjs</a>
                </li>
                <li class="nav-item">
                  <span class="badge badge-ring badge-purple"></span>
                  <a class="nav-link" href="#">Plugins</a>
                </li>
              </ul>
            </div>


            <div class="col-md-8 col-lg-9">

              <div class="media-list media-list-divided media-list-hover b-1 border-light bg-white">
                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="assets/img/avatar/2.jpg" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">Changing tags text colour</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-warning">Bootstrap</span>
                      <span class="divider-dash"></span>
                      Updated 3 mins ago by Hossein
                    </small>
                  </div>

                  <div class="fs-20 text-fade">02</div>
                </a>


                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="{% static 'img/avatar/default.jpg'  %}" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">Full height page and fixed footer</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-danger">General</span>
                      <span class="divider-dash"></span>
                      Updated 49 mins ago by Maryam
                    </small>
                  </div>

                  <div class="fs-20 text-fade">09</div>
                </a>


                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="{% static 'img/avatar/default.jpg' %}" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">Hyperlinks mysteriously adding extra characters, breaking link</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-info">Gruntjs</span>
                      <span class="divider-dash"></span>
                      Updated 2 hours ago by Tim
                    </small>
                  </div>

                  <div class="fs-20 text-fade">04</div>
                </a>


                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="{% static 'img/avatar/default.jpg'  %}" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">Removing Social Buttons/Icons from posts</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-danger">General</span>
                      <span class="divider-dash"></span>
                      Updated 3 hours ago by Sarah
                    </small>
                  </div>

                  <div class="fs-20 text-success" title="Answered" data-provide="tooltip">36</div>
                </a>


                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="{% static 'img/avatar/default.jpg'  %}" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">Page isn’t working. Probably plugin.php</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-purple">Plugins</span>
                      <span class="divider-dash"></span>
                      Updated 8 hours ago by Dusel
                    </small>
                  </div>

                  <div class="fs-20 text-fade">17</div>
                </a>


                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="{% static 'img/avatar/default.jpg'  %}" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">CSS editor without preview</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-purple">Plugins</span>
                      <span class="divider-dash"></span>
                      Updated 11 hours ago by Tim
                    </small>
                  </div>

                  <div class="fs-20 text-success" title="Answered" data-provide="tooltip">05</div>
                </a>


                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="{% static 'img/avatar/default.jpg'  %}" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">Mobile view correct on preview but not live view</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-warning">Bootstrap</span>
                      <span class="divider-dash"></span>
                      Updated 1 day ago by Hossein
                    </small>
                  </div>

                  <div class="fs-20 text-success" title="Answered" data-provide="tooltip">13</div>
                </a>


                <a class="media align-items-center" href="forum-single.html">
                  <img class="avatar" src="{% static 'img/avatar/default.jpg'  %}" alt="...">

                  <div class="media-body text-truncate">
                    <h5 class="fs-15">Make a theme retina ready (for the header image)</h5>
                    <small class="opacity-65 fw-300">
                      <span class="text-info">Gruntjs</span>
                      <span class="divider-dash"></span>
                      Updated 1 day ago by Maryam
                    </small>
                  </div>

                  <div class="fs-20 text-fade">01</div>
                </a>


              </div>


              <div class="flexbox align-items-center py-20">
                <span class="flex-grow text-right text-lighter pr-2">1-20 of 367</span>
                <nav>
                  <a class="btn btn-sm btn-square disabled" href="#"><i class="ti-angle-left"></i></a>
                  <a class="btn btn-sm btn-square" href="#"><i class="ti-angle-right"></i></a>
                </nav>
              </div>

              <br>

            </div>

          </div>
        </div>
      </div>